#!/bin/bash

# Retrieve arguments
domain=$1
path=$2
admin=$3
is_public=$4
app=respawn
final_path=/var/www/respawn

# Check that admin user is an existing account
sudo yunohost user list --json | grep -q "\"username\": \"$admin\""
if [[ ! $? -eq 0 ]]; then
echo "Error : the chosen admin user does not exist"
    exit 1
fi
sudo yunohost app setting shaarli admin -v $admin

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a respawn
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

# Install dependencies
sudo apt-get install php5-cli -y -qq

# Change user ID in configurations
sed -i "s@HOST@$domain@g" ../sources/index.html

# Copy files to the right place
sudo mkdir -p $final_path
sudo cp -R ../sources/* $final_path/

# Set permissions
sudo chmod 775 -R $final_path
sudo chown -hR $user:www-data $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/respawn.conf

# Make app public if necessary
sudo yunohost app setting $app is_public -v "$is_public"
if [ "$is_public" = "Yes" ];
then
    sudo yunohost app setting $app skipped_uris -v "/"
fi

# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app ssowatconf
