#!/bin/bash

domain=$(sudo yunohost app setting respawn domain)

sudo rm -rf /var/www/browsepass
sudo rm -f /etc/nginx/conf.d/$domain.d/browsepass.conf

sudo service nginx reload
sudo yunohost app ssowatconf
